In [2]:
import numpy as np

In [3]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [5]:
# Matrix Addition
matrix_add = np.add(matrix_a, matrix_b)
print("Matrix Addition:\n", matrix_add)

Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
# Matrix subtraction
matrix_sub = np.subtract(matrix_a, matrix_b)
print("Matrix Subtraction:\n", matrix_sub)

Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
# Element-wise multiplication
element_wise_mul = np.multiply(matrix_a, matrix_b)
print("Element-Wise Multiplication:\n", element_wise_mul)

Element-Wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [7]:
# Matrix multiplication (dot product)
matrix_mul = np.dot(matrix_a, matrix_b)
print("Matrix Multiplication (Dot Product):\n", matrix_mul)

Matrix Multiplication (Dot Product):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
